server:
  port: 8015
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.74.208:8001/eureka/
  instance:
    ip-address: 172.16.27.111
    hostname: ${eureka.instance.ip-address}
    lease-renewal-interval-in-seconds: 10      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  application:
    name: price-comparison-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.27.111:3306/price_comparison?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&useSSL=false
    username: root
    password: root123



mybatis:
  type-aliases-package: com.mortal.pricecomparison.entries
  mapper-locations: classpath:mybatis/mappers/*.xml,classpath:mybatis/mappers/spider/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-handlers-package: com.mortal.pricecomparison.mybatis_handler

logging:
  level:
    root: info
    com:
      mortal:
        pricecomparison:
          dao: debug
